name: setup-go
description: Setup Go

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
          go-version-file: 'backend/go.mod'
          cache: true
  