// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/keto-granola/keto-granola/internal/product"
	"sync"
)

// Ensure, that RepositoryMock does implement product.Repository.
// If this is not the case, regenerate this file with moq.
var _ product.Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of product.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked product.Repository
//		mockedRepository := &RepositoryMock{
//			GetProductFunc: func(ctx context.Context, ID pgtype.UUID) (*product.Product, error) {
//				panic("mock out the GetProduct method")
//			},
//		}
//
//		// use mockedRepository in code that requires product.Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// GetProductFunc mocks the GetProduct method.
	GetProductFunc func(ctx context.Context, ID pgtype.UUID) (*product.Product, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetProduct holds details about calls to the GetProduct method.
		GetProduct []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the ID argument value.
			ID pgtype.UUID
		}
	}
	lockGetProduct sync.RWMutex
}

// GetProduct calls GetProductFunc.
func (mock *RepositoryMock) GetProduct(ctx context.Context, ID pgtype.UUID) (*product.Product, error) {
	if mock.GetProductFunc == nil {
		panic("RepositoryMock.GetProductFunc: method is nil but Repository.GetProduct was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  ID,
	}
	mock.lockGetProduct.Lock()
	mock.calls.GetProduct = append(mock.calls.GetProduct, callInfo)
	mock.lockGetProduct.Unlock()
	return mock.GetProductFunc(ctx, ID)
}

// GetProductCalls gets all the calls that were made to GetProduct.
// Check the length with:
//
//	len(mockedRepository.GetProductCalls())
func (mock *RepositoryMock) GetProductCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockGetProduct.RLock()
	calls = mock.calls.GetProduct
	mock.lockGetProduct.RUnlock()
	return calls
}
