name: Backend

on:
  pull_request:
    branches: [main]
    paths:
      - backend/**

jobs:
  lint:
    defaults:
      run:
        working-directory: backend

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: ./.github/actions/build-frontend

      - uses: ./.github/actions/setup-go

      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2
          working-directory: backend
          args: --timeout 5m

  test:
    defaults:
      run:
        working-directory: backend

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - uses: ./.github/actions/build-frontend

      - uses: ./.github/actions/setup-go
      - run: make test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: docker/setup-buildx-action@v3

      - uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      - run: make docker/ci-build