// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/keto-granola/server/internal/product"
	"sync"
)

// Ensure, that RepositoryMock does implement product.Repository.
// If this is not the case, regenerate this file with moq.
var _ product.Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of product.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked product.Repository
//		mockedRepository := &RepositoryMock{
//			InsertProductFunc: func(ctx context.Context, params *product.CreateProductParams) (*product.Product, error) {
//				panic("mock out the InsertProduct method")
//			},
//		}
//
//		// use mockedRepository in code that requires product.Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// InsertProductFunc mocks the InsertProduct method.
	InsertProductFunc func(ctx context.Context, params *product.CreateProductParams) (*product.Product, error)

	// calls tracks calls to the methods.
	calls struct {
		// InsertProduct holds details about calls to the InsertProduct method.
		InsertProduct []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *product.CreateProductParams
		}
	}
	lockInsertProduct sync.RWMutex
}

// InsertProduct calls InsertProductFunc.
func (mock *RepositoryMock) InsertProduct(ctx context.Context, params *product.CreateProductParams) (*product.Product, error) {
	if mock.InsertProductFunc == nil {
		panic("RepositoryMock.InsertProductFunc: method is nil but Repository.InsertProduct was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *product.CreateProductParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockInsertProduct.Lock()
	mock.calls.InsertProduct = append(mock.calls.InsertProduct, callInfo)
	mock.lockInsertProduct.Unlock()
	return mock.InsertProductFunc(ctx, params)
}

// InsertProductCalls gets all the calls that were made to InsertProduct.
// Check the length with:
//
//	len(mockedRepository.InsertProductCalls())
func (mock *RepositoryMock) InsertProductCalls() []struct {
	Ctx    context.Context
	Params *product.CreateProductParams
} {
	var calls []struct {
		Ctx    context.Context
		Params *product.CreateProductParams
	}
	mock.lockInsertProduct.RLock()
	calls = mock.calls.InsertProduct
	mock.lockInsertProduct.RUnlock()
	return calls
}
